
CREATE OR REPLACE STREAM CUSTOMER_TABLE_CHANGES ON TABLE CUSTOMER;

CREATE OR REPLACE STORAGE INTEGRATION S3_INIT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN='arn:aws:iam::798585594565:role/SNOWFLAKE-S3-CONNECTION'
    STORAGE_ALLOWED_LOCATIONS = ('s3://dw-devi/stream_data/')
    COMMENT  =  'CREATE CONNECTION TO S3'

DESC INTEGRATION S3_INIT

CREATE OR REPLACE STAGE SCD_DEMO.SCD2.CUSTOMER_EXT_STAGE
URL = 's3://dw-devi/stream_data/'
STORAGE_INTEGRATION=S3_INIT

CREATE OR REPLACE FILE FORMAT SCD_DEMO.SCD2.CSV
TYPE =  CSV,
FIELD_DELIMITER=","
SKIP_HEADER = 1;

SHOW STAGES;
LIST @CUSTOMER_EXT_STAGE

CREATE  OR  REPLACE PIPE CUSTOMER_S3_PIPE
auto_ingest=True
AS
COPY INTO CUSTOMER_RAW
FROM @CUSTOMER_EXT_STAGE
FILE_FORMAT=CSV

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('customer_s3_pipe')

select count(*) from customer_raw

TRUNCATE CUSTOMER_RAW

///
MERGE INTO CUSTOMER C
USING CUSTOMER_RAW CR
    ON C.CUSTOMER_ID = CR.CUSTOMER_ID
WHEN  MATCHED AND C.CUSTOMER_ID<>CR.CUSTOMER_ID OR
                  C.FIRST_NAME <> CR.FIRST_NAME OR
                  C.LAST_NAME <> CR.LAST_NAME OR
                  C.EMAIL <> CR.EMAIL OR
                  C.STREET <> CR.STREET OR
                  C.CITY <> CR.CITY OR
                  C.STATE <> CR.STATE OR
                  C.COUNTRY <> CR.COUNTRY THEN UPDATE
        SET C.CUSTOMER_ID = CR.CUSTOMER_ID,
        C.FIRST_NAME = CR.FIRST_NAME,
        C.LAST_NAME = CR.LAST_NAME,
        C.EMAIL = CR.EMAIL,
        C.STREET = CR.STREET,
        C.CITY = CR.CITY,
        C.STATE = CR.STATE,
        C.COUNTRY = CR.COUNTRY,
        UPDATE_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (
        C.CUSTOMER_ID,
        C.FIRST_NAME,
        C.LAST_NAME,
        C.EMAIL,
        C.STREET,
        C.CITY,
        C.STATE,
        C.COUNTRY
    )
VALUES(
    CR.CUSTOMER_ID,
    CR.FIRST_NAME,
    CR.LAST_NAME,
    CR.EMAIL,
    CR.STREET,
    CR.CITY,
    CR.STATE,
    CR.COUNTRY
)

SELECT COUNT(*) FROM  CUSTOMER;

SELECT * FROM CUSTOMER

TRUNCATE CUSTOMER




